AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    sam first lambda

    Sample SAM Template for sam first lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Api:
        Cors:
            AllowMethods: "'GET,POST,OPTIONS'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Origin,Accept,Cookie'"
            AllowOrigin: "'http://localhost:5173'"
            AllowCredentials: true
    Function:
        Timeout: 60

Resources:
    # handle the layers
    SharedUsernameLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: get username layer
            Description: Shared Node.js get username layer
            ContentUri: ./layers/cookie
            CompatibleRuntimes:
                - nodejs18.x
    SharedTextLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: text layer
            Description: Shared Node.js get text layer
            ContentUri: ./layers/text
            CompatibleRuntimes:
                - nodejs18.x

    # handle the lambda functions
    newAssociateFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/add_new_associate/
            Handler: index.handler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                newAssociate:
                    Type: Api
                    Properties:
                        Path: /addAssociate
                        Method: post
    newAppointmentFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/create_new_appointment/
            Handler: index.handler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedTextLayer
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
                    NODE_PATH: "/opt/nodejs/"
            Architectures:
                - x86_64
            Events:
                newAppointment:
                    Type: Api
                    Properties:
                        Path: /createNewAppointment
                        Method: post
    loginFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/login/
            Handler: index.handler
            Runtime: nodejs18.x
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
                    NODE_PATH: "/opt/nodejs/"
            Architectures:
                - x86_64
            Events:
                Login:
                    Type: Api
                    Properties:
                        Path: /login
                        Method: post
    retrieveAppointmentsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/retrieve_appointments/
            Handler: index.handler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
                    NODE_PATH: "/opt/nodejs/"
            Architectures:
                - x86_64
            Events:
                retrieveAppointments:
                    Type: Api
                    Properties:
                        Path: /retrieveAppointments
                        Method: post
    sendAppointmentRemindersFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/send_appointment_reminders/
            Handler: index.handler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedTextLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
                    NODE_PATH: "/opt/nodejs/"
            Architectures:
                - x86_64
            Events:
                sendAppointmentReminders:
                    Type: Api
                    Properties:
                        Path: /sendAppointmentReminders
                        Method: post
                        
    isLoggedInFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/is_logged_in/
            Handler: index.handler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
                    NODE_PATH: "/opt/nodejs/"
            Architectures:
                - x86_64
            Events:
                isLoggedIn:
                    Type: Api
                    Properties:
                        Path: /isLoggedIn
                        Method: get
    deleteAppointmentFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/delete_appointment/
            Handler: index.handler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
                    NODE_PATH: "/opt/nodejs/"
            Architectures:
                - x86_64
            Events:
                deleteAppointment:
                    Type: Api
                    Properties:
                        Path: /deleteAppointment
                        Method: post
    retrieveAssociateFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: lambda_functions/retrieve_associate/
            Handler: index.handler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
                    NODE_PATH: "/opt/nodejs/"
            Architectures:
                - x86_64
            Events:
                deleteAppointment:
                    Type: Api
                    Properties:
                        Path: /retrieveAssociate
                        Method: get

