AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    sam first lambda

    Sample SAM Template for sam first lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Resources:
    # handle the layers
    SharedUsernameLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: get username layer
            Description: Shared Node.js get username layer
            ContentUri: ./layers/cookie
            CompatibleRuntimes:
                - nodejs18.x
    SharedTextLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: text layer
            Description: Shared Node.js get text layer
            ContentUri: ./layers/text
            CompatibleRuntimes:
                - nodejs18.x

    # handle the lambda functions
    newAssociateFunction:
        Type: AWS::Serverless::Function
        Properties:
            Timeout: 15
            CodeUri: lambda_functions/add_new_associate/
            Handler: index.lambdaHandler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                newAssociate:
                    Type: Api
                    Properties:
                        Path: /addAssociate
                        Method: post
    newAppointmentFunction:
        Type: AWS::Serverless::Function
        Properties:
            Timeout: 15
            CodeUri: lambda_functions/create_new_appointment/
            Handler: index.lambdaHandler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedTextLayer
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
            Architectures:
                - x86_64
            Events:
                newAppointment:
                    Type: Api
                    Properties:
                        Path: /createNewAppointment
                        Method: post
    loginFunction:
        Type: AWS::Serverless::Function
        Properties:
            Timeout: 15
            CodeUri: lambda_functions/login/
            Handler: index.lambdaHandler
            Runtime: nodejs18.x
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
            Architectures:
                - x86_64
            Events:
                Login:
                    Type: Api
                    Properties:
                        Path: /login
                        Method: post
    retrieveAppointmentsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Timeout: 15
            CodeUri: lambda_functions/retrieve_appointments/
            Handler: index.lambdaHandler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
            Architectures:
                - x86_64
            Events:
                retrieveAppointments:
                    Type: Api
                    Properties:
                        Path: /retrieveAppointments
                        Method: post
    sendAppointmentRemindersFunction:
        Type: AWS::Serverless::Function
        Properties:
            Timeout: 15
            CodeUri: lambda_functions/send_appointment_reminders/
            Handler: index.lambdaHandler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedTextLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
            Architectures:
                - x86_64
            Events:
                sendAppointmentReminders:
                    Type: Api
                    Properties:
                        Path: /sendAppointmentReminders
                        Method: post
    isLoggedInFunction:
        Type: AWS::Serverless::Function
        Properties:
            Timeout: 15
            CodeUri: lambda_functions/is_logged_in/
            Handler: index.lambdaHandler
            Runtime: nodejs18.x
            Layers:
                - !Ref SharedUsernameLayer
            Environment:
                Variables:
                    JWT_SECRET_KEY_VALUE: "flj3289gnw89jnfgjnw33fn33dfs"
            Architectures:
                - x86_64
            Events:
                isLoggedIn:
                    Type: Api
                    Properties:
                        Path: /isLoggedIn
                        Method: get
