version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - echo "Installing Node.js dependencies..."
            - npm install

    build:
        commands:
            - echo "Zipping deployment packages..."
            - mkdir lambda_zips
            - mkdir lambda_zips/add_new_associate
            - cp sam-app/lambda_functions/add_new_associate/index.js lambda_zips/add_new_associate/index.mjs
            - mkdir lambda_zips/create_new_appointment
            - cp sam-app/lambda_functions/create_new_appointment/index.js lambda_zips/create_new_appointment/index.mjs
            - mkdir lambda_zips/login
            - cp sam-app/lambda_functions/login/index.js lambda_zips/login/index.mjs
            - mkdir lambda_zips/retrieve_appointments
            - cp sam-app/lambda_functions/retrieve_appointments/index.js lambda_zips/retrieve_appointments/index.mjs
            - mkdir lambda_zips/send_appointment_reminders
            - cp sam-app/lambda_functions/send_appointment_reminders/index.js lambda_zips/send_appointment_reminders/index.mjs
            - mkdir lambda_zips/is_logged_in
            - cp sam-app/lambda_functions/is_logged_in/index.js lambda_zips/is_logged_in/index.mjs
            - mkdir lambda_zips/delete_appointment
            - cp sam-app/lambda_functions/delete_appointment/index.js lambda_zips/delete_appointment/index.mjs
            - mkdir lambda_zips/retrieve_associate
            - cp sam-app/lambda_functions/retrieve_associate/index.js lambda_zips/retrieve_associate/index.mjs
            - cd lambda_zips
            - for dir in */; do zip -r9 "${dir%/}.zip" "$dir"; done
            - echo "Zipping deployment package for Lambda layer..."
            - cd ../sam-app/layers/cookie/nodejs/node_modules/get_username_from_cookie
            - zip -r9 ../../../../../../lambda_zips/getUsernameLayer.zip .
            - cd ../../../../../../lambda_zips
            - cd ../sam-app/layers/text/nodejs/node_modules/send-text-message
            - zip -r9 ../../../../../../lambda_zips/getTextLayer.zip .
            - cd ../../../../../../lambda_zips

    post_build:
        commands:
            - echo "Updating Lambda Functions..."
            - aws lambda update-function-code --function-name addNewAssociate --zip-file fileb://newAssociate.zip
            - aws lambda update-function-code --function-name createNewAppointment --zip-file fileb://newAppointment.zip
            - aws lambda update-function-code --function-name logAssociateIn --zip-file fileb://login.zip
            - aws lambda update-function-code --function-name retrieveAppointments --zip-file fileb://retrieveAppointments.zip
            - aws lambda update-function-code --function-name sendAppointmentReminders --zip-file fileb://sendAppointmentReminders.zip
            - aws lambda update-function-code --function-name isLoggedIn --zip-file fileb://isLoggedIn.zip
            - aws lambda update-function-code --function-name deleteAppointments --zip-file fileb://deleteAppointment.zip
            - aws lambda update-function-code --function-name retrieveAssociate --zip-file fileb://isLoggedIn.zip
            - aws lambda publish-layer-version --layer-name getUsernameLayer --description "Shared Node.js get username layer" --zip-file fileb://getUsernameLayer.zip --compatible-runtimes nodejs18.x
            - aws lambda publish-layer-version --layer-name getTextLayer --description "Shared Node.js text layer" --zip-file fileb://getTextLayer.zip --compatible-runtimes nodejs18.x
            - echo "DONE NOW!!"
