version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install

  build:
    commands:
      - echo "Zipping deployment packages..."
      - mkdir newAssociate newAppointment login retrieveAppointments sendAppointmentReminders
      - cd lambda_functions/
      - cp add_new_associate/index.js newAssociate/
      - cp create_new_appointment/index.js newAppointment/
      - cp login/index.js login/
      - cp retrieve_appointments/index.js retrieveAppointments/
      - cp send_appointment_reminders/index.js sendAppointmentReminders/
      - cd ../newAssociate
      - zip -r9 newAssociate.zip .
      - cd ../newAppointment
      - zip -r9 newAppointment.zip .
      - cd ../login
      - zip -r9 login.zip .
      - cd ../retrieveAppointments
      - zip -r9 retrieveAppointments.zip .
      - cd ../sendAppointmentReminders
      - zip -r9 sendAppointmentReminders.zip .

  post_build:
    commands:
      - echo "Updating Lambda Function..."
      - aws lambda update-function-code --function-name addNewAssociate --zip-file fileb://newAssociate.zip
      - aws lambda update-function-code --function-name createNewAppointment --zip-file fileb://newAppointment.zip
      - aws lambda update-function-code --function-name logAssociateIn --zip-file fileb://login.zip
      - aws lambda update-function-code --function-name retrieveAppointments --zip-file fileb://retrieveAppointments.zip
      - aws lambda update-function-code --function-name sendAppointmentReminders --zip-file fileb://sendAppointmentReminders.zip
      - echo "DONE!!"
