version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Use the desired Node.js version
    commands:
      - npm install -g serverless # Install Serverless framework globally

  build:
    commands:
      - serverless deploy # Deploy using Serverless framework

artifacts:
  files:
    - '**/*' # Include all files in the deployment package
